version: "3.8"

services:
  web:
    build: .
    ports:
      - "4201:80"
    volumes:
      - ./public:/var/www/html/public
      - ./logs:/var/www/html/logs
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
